version = 1

[[annotations]]
path = [
 ".circleci/config.yml",
 ".formatter.exs",
 ".github/dependabot.yml",
 ".gitignore",
 "CHANGELOG.md",
 "NOTICE",
 "REUSE.toml",
 "mix.exs",
 "mix.lock"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "CC0-1.0"

[[annotations]]
path = [
 "README.md"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2018 Frank Hunleth"
SPDX-License-Identifier = "BSD-2-Clause"

[[annotations]]
path = [
 "src/pkcs11.h"
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2015-2016 Yubico AB"
SPDX-License-Identifier = "BSD-2-Clause"
